from typing import NewType


class ArgumentType:
    """Registry of argument types"""

    # signals
    StaticNumericSignal = NewType("StaticNumericSignalArg", str)
    StaticStringSignal = NewType("StaticStringSignalArg", str)
    TimeNumericSignal = NewType("TimeNumericSignalArg", str)
    TimeStringSignal = NewType("TimeStringSignalArg", str)
    DepthNumericSignal = NewType("DepthNumericSignalArg", str)
    DepthStringSignal = NewType("DepthStringSignalArg", str)
    PVTSignal = NewType("PVTSignalArg", str)

    # general types
    StringValue = NewType("StringValueArg", str)
    StringOptions = NewType("StringOptionsArg", str)
    ItemName = NewType("ItemNameArg", ArgumentItemType)
    ItemOptions = NewType("ItemOptionsArg", ArgumentItemType)

    # specific types
    TagEntries = NewType("TagEntriesArg", str)

class ArgumentItemType:
    BlobFile = NewType("BlobFileArg", str)
    Calculation = NewType("CalculationArg", str)
    ChartDefinition = NewType("ChartDefinitionArg", str)
    CleansingCalculation = NewType("CleansingCalculationArg", str)
    CleansingScript = NewType("CleansingScriptArg", str)
    Context = NewType("ContextArg", str)
    CustomWorkflowActivity = NewType("CustomWorkflowActivityArg", str)
    Dashboard = NewType("DashboardArg", str)
    DataConnection = NewType("DataConnectionArg", str)
    DataGrid = NewType("DataGridArg", str)
    DataIntegrationSession = NewType("DataIntegrationSessionArg", str)
    DataIntegrationSet = NewType("DataIntegrationSetArg", str)
    DataSource = NewType("DataSourceArg", str)
    DCA = NewType("DCAArg", str)
    Entity = NewType("EntityArg", str)
    EntitySet = NewType("EntitySetArg", str)
    EntityType = NewType("EntityTypeArg", str)
    EventCalculation = NewType("EventCalculationArg", str)
    EventSubscription = NewType("EventSubscriptionArg", str)
    FilterDefinition = NewType("FilterDefinitionArg", str)
    Hierarchy = NewType("HierarchyArg", str)
    Label = NewType("LabelArg", str)
    Message = NewType("MessageArg", str)
    MLModel = NewType("MLModelArg", str)
    PivotTable = NewType("PivotTableArg", str)
    Plot = NewType("PlotArg", str)
    PowerBIItem = NewType("PowerBIItemArg", str)
    ProcessTemplate = NewType("ProcessTemplateArg", str)
    PSharpScript = NewType("PSharpScriptArg", str)
    PythonWorkflowActivity = NewType("PythonWorkflowActivityArg", str)
    ReferenceTable = NewType("ReferenceTableArg", str)
    RWorkflowActivity = NewType("RWorkflowActivityArg", str)
    Scenario = NewType("ScenarioArg", str)
    Scope = NewType("ScopeArg", str)
    Signal = NewType("SignalArg", str)
    Snapshot = NewType("SnapshotArg", str)
    Tag = NewType("TagArg", str)
    TagEntry = NewType("TagEntryArg", str)
    Ticket = NewType("TicketArg", str)
    TicketTimeInterval = NewType("TicketTimeIntervalArg", str)
    Unit = NewType("UnitArg", str)
    Unknown = NewType("UnknownArg", str)
    User = NewType("UserArg", str)
    UserGroup = NewType("UserGroupArg", str)
    UserSetting = NewType("UserSettingArg", str)
    WebWorkflowActivity = NewType("WebWorkflowActivityArg", str)
    Workflow = NewType("WorkflowArg", str)
    WorkflowSchedule = NewType("WorkflowScheduleArg", str)
    Workspace = NewType("WorkspaceArg", str)
    WorkspaceValue = NewType("WorkspaceValueArg", str)
    WorkspacePackage = NewType("WorkspacePackageArg", str)
